// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"576","screenHeight":"288","changeWindowWidthTo":"1152","changeWindowHeightTo":"576","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"GALV_CamControl","status":true,"description":"Allows greater control over where the game camera is focused. View HELP for plugin commands.","parameters":{"Tile Size":"48"}},
{"name":"NearEventSensor","status":true,"description":"周辺イベント感知プラグイン","parameters":{"DefaultFlash":"true","DefaultBalloon":"0","DisableEmpty":"true","SensorDistance":"2","FlashColor":"{\"Red\":\"255\",\"Green\":\"255\",\"Blue\":\"255\",\"Alpha\":\"255\"}","FlashDuration":"60","BalloonInterval":"15","WaitForBalloon":"true","ConsiderationDir":"false","ApplyPlayer":"false","EraseWhenAway":"false"}}
];
