// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"AG_CharacterNoisySteps","status":true,"description":"Characters will produce stepping sound effects when they move on the map terrain.","parameters":{"Player Step SE Volume":"40","Events Step SE Volume":"20","Step SE Pitch":"100","Pitch Variance":"5","Pan Variance":"40","Disable Player Noisy Steps Switch ID":"0","Disable Events Noisy Steps Switch ID":"0","Terrain Tag 0 SE":"","Terrain Tag 1 SE":"concrete","Terrain Tag 2 SE":"sand","Terrain Tag 3 SE":"carpet","Terrain Tag 4 SE":"grass","Terrain Tag 5 SE":"metal","Terrain Tag 6 SE":"wood","Terrain Tag 7 SE":"dirt","Size Tag Pitch Increment":"40","Special Tag 1 SE":"robot","Special Tag 2 SE":"wheels","Special Tag 3 SE":"claws","Special Tag 4 SE":"chains","Special Tag 5 SE":"dragged\r"}},
{"name":"GALV_CamControl","status":true,"description":"Allows greater control over where the game camera is focused. View HELP for plugin commands.","parameters":{"Tile Size":"10"}}
];
